python ../train_ldm_unet.py \
    --latent_data_dir ../data \
    --save_dir ../model_runs/ldm_unet_run_1 \
    --latent_dim 32 \
    --latent_size 16 \
    --epochs 100 \
    --batch_size 32 \
    --lr 1e-4 \
    --num_workers 4 \
    --noise_steps 1000 \
    --noise_schedule cosine